### ISSUE TITLE
pip installation fails for pip 21.0.1

### ISSUE THREAD

**Issue by Alex-Lewandowski** [ASFHyP3/mkdocs-asf-theme#24]
**Describe the bug**

python -m pip install mkdocs-asf-theme and pip install mkdocs-asf-theme both fail with pip 21.0.1

ERROR: Could not find a version that satisfies the requirement mkdocs-asf-theme
ERROR: No matching distribution found for mkdocs-asf-theme

**To Reproduce**
install pip 21.0.1 and run python -m pip install mkdocs-asf-theme

**Expected behavior**

I expected pip to find and install the package

**Additional context**

I created a conda env that installed pip 20.3.3 (which was current version at the time of the last mkdocs-asf-theme release) and it installed with no trouble.

**Comment by jhkennedy** [comment]
I could not reproduce this: 

```sh
$ conda create -y -n foobar python=3.8 pip=21
...

$ conda activate foobar
$ python -m pip --version
pip 21.0.1 from /.../miniconda3/envs/foobar/lib/python3.8/site-packages/pip (python 3.8)

$ python -m pip install mkdocs-asf-theme
...
Installing collected packages: tqdm, regex, joblib, future, click, nltk, lunr, PyYAML, Markdown, livereload, pymdown-extensions, mkdocs-material-extensions, mkdocs, mkdocs-material, mkdocs-asf-theme
Successfully installed Markdown-3.3.3 PyYAML-5.4.1 click-7.1.2 future-0.18.2 joblib-1.0.1 livereload-2.6.3 lunr-0.5.8 mkdocs-1.1.2 mkdocs-asf-theme-0.2.1 mkdocs-material-6.2.8 mkdocs-material-extensions-1.0.1 nltk-3.5 pymdown-extensions-8.1.1 regex-2020.11.13 tqdm-4.56.2

```

When env were you using `pip` in and how'd you set it up?

**Comment by Alex-Lewandowski** [comment]
I was able to reproduce the error with this env: conda create -c conda-forge -y -n foobar python=3.7 pip=21.0.1

**Comment by jhkennedy** [comment]
@Alex-Lewandowski `asf-mkdocs-theme` requires python 3.8+:
![image](https://user-images.githubusercontent.com/7882693/107981055-e0e2a400-6f6d-11eb-9126-3da85b2fde9e.png)

Do you need python 3.7? It's only a couple line change to support lower (but adds a dependency).
