### ISSUE TITLE
Fix remaining style differences since upgrading `mkdocs-material`

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/mkdocs-asf-theme#40]
**Jira:** https://asfdaac.atlassian.net/browse/TOOL-2246

*Note: The above link is accessible only to members of ASF.*

----------------------------------------------------------------------------------------------------

Here are the remaining style differences between `hyp3-docs` website using [mkdocs-asf-theme v0.2.4](https://github.com/ASFHyP3/mkdocs-asf-theme/releases/tag/v0.2.4) and the currently unreleased version of `mkdocs-asf-theme` that uses the latest version of `mkdocs-material`:

- [x] The sidebar menu headings ("HyP3" and "Table of contents") have a lighter background color than the rest of the `hyp3-docs` page. Inspecting with Firefox's builtin color inspector reveals that it's actually a subtle gradient. Ideally it would be nice to get rid of it because it does not appear in the current version of the site, but I've exhausted my CSS knowledge attempting to identify where exactly the gradient is specified.
- ~~The sidebar menu visible area appears to have shrunk slightly, so that not as many menu items remain visible as you scroll into the footer. I have no idea how to fix this.~~
- ~~Certain elements (e.g. the "Alaska Satellite Facility's Hybrid Pluggable Processing Pipeline" sub-heading and the "HyP3" title in the header) are now bold. I don't know how much we care about reverting this.~~
- [x] Scrolling table of contents results in "Table of contents" overlapping the contents (give sidebar menu headings same background color as surrounding page, maybe restore box shadow)

We should fix any of these that we feel are important and strike through those that are not important.

**Comment by jhkennedy** [comment]
The sidebar menu headings should be fixed with #42

**Comment by jhkennedy** [comment]
> The sidebar menu visible area appears to have shrunk slightly, so that not as many menu items remain visible as you scroll into the footer. I have no idea how to fix this.

Can you post a screenshot? I'm seeing the opposite -- on the home page, if I open a few menu items and then scroll down to the bottom so the whole footer is showing, I see a height of 2156.3 px for the current website and a hight of 2158.3 for the website with the updated theme. Either way, the 2 px doesn't concern me.

**Comment by jtherrmann** [comment]
@jhkennedy Actually, I think it was just a quirk of my zoom settings. Resetting to 100% zoom makes everything normal.
