### ISSUE TITLE
Google Analytics site settings

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/mkdocs-asf-theme#9]
Consider adding ~~`copyright` and~~ `google_analytics` to https://github.com/ASFHyP3/asf-mkdocs-theme/blob/develop/asf_theme/mkdocs_theme.yml

e.g. https://github.com/ASFHyP3/ASFHyP3/blob/main/mkdocs.yml#L5

**Comment by jhkennedy** [comment]
Copyright is a little more complicated, so I've moved that to #10
